#
# Makefile for grip sensors
#

obj-$(CONFIG_SENSORS_A96T396)		+= a96t396.o
obj-$(CONFIG_SENSORS_ISG5320A)	    += isg5320a.o
obj-$(CONFIG_SENSORS_ISG5320A_SUB)	+= isg5320a_sub.o
obj-$(CONFIG_SENSORS_SX9380)  		+= sx938x.o
obj-$(CONFIG_SENSORS_ISG6320)	    += isg6320.o
